services:
    laravel:
        ports:
            - "8000:8000"
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        environment:
            - DB_CONNECTION=${DB_CONNECTION:-pgsql}
            - DB_DATABASE=${DB_DATABASE:-laravel}
            - DB_USERNAME=${DB_USERNAME:-dev}
            - DB_PASSWORD=${DB_PASSWORD:-dev}
            - DB_HOST=${DB_HOST:-pgsql}
            - APP_ENV=${APP_ENV:-local}
            - APP_DEBUG=${APP_DEBUG:-true}
        depends_on:
            - pgsql
    pgsql:
        image: 'postgres:17-alpine'
        expose:
            - 5432

        environment:
            POSTGRES_DB: '${DB_DATABASE:-laravel}'
            POSTGRES_USER: '${DB_USERNAME:-dev}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-dev}'
        volumes:
            - pgdata:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE:-laravel}", "-U", "${DB_USERNAME:-dev}"]
            retries: 3
            timeout: 5s
volumes:
  pgdata:
    driver: local